### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by TheFox** [rom-rb/rom-yaml#7]
Where can I find examples of a real usecase? `spec/integration/adapter_spec.rb` is not really an example code. It is not helpful. How can I create a new yaml file for a Relation using the YAML Gateway?

**Comment by flash-gordon** [comment]
@TheFox there are two basic options you have: define all relations in a single file or create separate files per relation.
In the first case a complete example would be 

data.yml
```yaml
users:
  - name: 'Jane'
    email: 'jane@doe.org'
  - name: 'John'
    email: 'john@acme.com'
```


```ruby

require 'rom-yaml'

rom = ROM.container(:yaml, File.join(__dir__, 'data.yml')) do |c|
  c.relation(:users) do
    schema do
      attribute :name, ROM::Types::String
      attribute :email, ROM::Types::String
    end
  end
end

p rom.relation(:users).to_a
# [{:name=>"Jane", :email=>"jane@doe.org"}, {:name=>"John", :email=>"john@acme.com"}]
```

or as always you can make a separate class
```ruby
require 'rom-yaml'

class Users < ROM::Relation[:yaml]
  dataset :users

  schema do
    attribute :name, ROM::Types::String
    attribute :email, ROM::Types::String
  end
end

rom = ROM.container(:yaml, File.join(__dir__, 'data.yml')) do |c|
  c.register_relation(Users)
end

p rom.relation(:users).to_a
# [{:name=>"Jane", :email=>"jane@doe.org"}, {:name=>"John", :email=>"john@acme.com"}]
```

**Comment by TheFox** [comment]
@flash-gordon Thank you for your fast response. How would it look like if I doesn't already have a `data.yml`, when creating a new user via the Repository? Something like `create_table` for rom-sql but for YAML. ROM complains when I don't have a `data.yml` in the first place.

**Comment by flash-gordon** [comment]
@TheFox at this point this is not possible because the adapter is lack of commands, I filed an issue about this https://github.com/rom-rb/rom-yaml/issues/8

**Comment by TheFox** [comment]
@flash-gordon I see. Thank you for your help.
